sudo: false
language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - pypy

cache:
    apt: true
    pip: true
    directories:
        - $HOME/download-cache

addons:
    apt_packages:
        - binutils
        - default-jdk
        - gdal-bin
        - libgdal1h
        - libgeos-c1
        - libproj-dev
        - wajig

before_install:
    - mkdir -p $HOME/download-cache

install:
    - pip install requests "Django${DJANGO_VERSION}" coveralls
    - python setup.py clean build install

before_script:
    - BACKGROUND_SOLR=true test_searchstack/solr_tests/server/start-solr-test-server.sh

script:
    - python test_searchstack/solr_tests/server/wait-for-solr
    - python setup.py nosetests

after_success:
    - coveralls

env:
    matrix:
        - DJANGO_VERSION=">=1.8,<1.9"
        - DJANGO_VERSION=">=1.9,<1.10"

matrix:
    allow_failures:
        - python: "pypy"

services:
    - elasticsearch

notifications:
    email: false
